language: python
python:
  - "2.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-ble-led
  - PLATFORMIO_PROJECT_DIR=examples/mbed-ble-thermometer
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-dsp
  - PLATFORMIO_PROJECT_DIR=examples/mbed-events
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos
  - PLATFORMIO_PROJECT_DIR=examples/mbed-serial

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: K16XOvJ+WtAWkif7bB88bPTTeNzM5vAFHHEzSe5UF6vjsyhM7PEITbwB6TCB9upBTsgpBLO8ep98MrOhISnqRRbPXm5G0UDMbxVfsUtrFgR/+YnzF0+GrcMYYYI0vmPE5voM2INjDVca1m8La8udkCQjxojIrIKbxDFnvAgn6irVzGgP4THZEsRL55Nzgun79QALp2F1oiNv+YtZW7sgz7myRk4A1HKYs0cN5JkvbsizS91KYUaGFZwl98kerHykk8UVtUr1UT4xp5ZQnfrvbYRqTL+z4b9Xzri3KmTUHak2v1GyHk1ZJNFDI2T0UvlwTUmVdltFP3La9CMN7lKlOma2HiTKv433mtpU/9+x+iouBZ6ThyVXxxSrQyF2nUtFdp10RTrVzWu8YQJyeMYiOm6Rs6zfFrtNXQg4AI7qdEJmh1TyKreXiia4iSd6A1W8zQfqDsCZhd9EwBfu2cA25+2T52kW/N1ZuVPNr4XXYWXsYjXw6cVNxDHJA0s+uCSxnEif/oMtwS29mwe73Y/26rwli5QWhKn1aWGNCAVvikpm/xVBcQzj7W79Ch4o5NEHGqAIZtDHmDNQkMwPUN3u8sjqescXG/jP9SAuAxmpbu4+FQFr9kj8JHLXdzHexvL3I6D1WiVBbVQBiyzvWFJBzNKou5PX9H069eswr632jhY=
    on_failure: always
    on_success: change
